name: Linting and Testing for Continuous Integration

on:
  push:
  pull_request:
    branches:
      - master

jobs:
  JavaFormat: # Format Java Code to meet the Google Java Style Guide
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2 # v2 minimum required
      - name: Use Java 8
        uses: actions/setup-java@v1
        with:
          java-version: "8"
      - name: Format Java Code
        uses: axel-op/googlejavaformat-action@v3
        with:
          args: "--replace"
          

  BuildAndTest:  # Check that the current Code can be built and all the current 
  # tests pass. This check is a safegaurd to ensure that the master branch is
  # never broken. BuildAndTest is set to be a compulsory check that must pass
  # before any merges are made to master. This can be changed in the branch
  # protection settings.
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2 
    - name: Use Java 8
      uses: actions/setup-java@v1
      with:
        java-version: "8"

    - name: Build and check for errors
      run: ./xic-build
