
//----------------------------------------------------
// The following code was generated by CUP v0.11b 20150326
//----------------------------------------------------

package apd67.parser;

/** CUP generated class containing symbol constants. */
public class sym {
  /* terminals */
  public static final int USCORE = 39;
  public static final int LT = 23;
  public static final int MIN_INT = 45;
  public static final int MINUS = 19;
  public static final int FUNC_DEF = 43;
  public static final int SEMICOLON = 16;
  public static final int ELSE = 3;
  public static final int INDEX = 38;
  public static final int ID = 46;
  public static final int IF = 2;
  public static final int LPAREN = 9;
  public static final int BLOCK = 41;
  public static final int TRUE = 6;
  public static final int RPAREN = 10;
  public static final int EQ = 27;
  public static final int BOOL_TYPE = 5;
  public static final int NOT = 8;
  public static final int RBRACK = 14;
  public static final int GEQ = 26;
  public static final int RBRACE = 12;
  public static final int LBRACK = 13;
  public static final int FUNC_CALL = 40;
  public static final int AND = 29;
  public static final int NEGATIVE = 37;
  public static final int LTE = 24;
  public static final int INT_TYPE = 4;
  public static final int LBRACE = 11;
  public static final int PLUS = 18;
  public static final int HTIMES = 35;
  public static final int LENGTH = 34;
  public static final int CHAR = 48;
  public static final int error = 1;
  public static final int ASSIGN = 31;
  public static final int INT = 44;
  public static final int RETURN = 33;
  public static final int EOF = 0;
  public static final int COMMA = 17;
  public static final int MOD = 22;
  public static final int OR = 30;
  public static final int TIMES = 20;
  public static final int USE = 36;
  public static final int COLON = 15;
  public static final int GT = 25;
  public static final int DIV = 21;
  public static final int STRING = 47;
  public static final int FALSE = 7;
  public static final int WHILE = 32;
  public static final int NEQ = 28;
  public static final int IXI = 42;
  public static final String[] terminalNames = new String[] {
  "EOF",
  "error",
  "IF",
  "ELSE",
  "INT_TYPE",
  "BOOL_TYPE",
  "TRUE",
  "FALSE",
  "NOT",
  "LPAREN",
  "RPAREN",
  "LBRACE",
  "RBRACE",
  "LBRACK",
  "RBRACK",
  "COLON",
  "SEMICOLON",
  "COMMA",
  "PLUS",
  "MINUS",
  "TIMES",
  "DIV",
  "MOD",
  "LT",
  "LTE",
  "GT",
  "GEQ",
  "EQ",
  "NEQ",
  "AND",
  "OR",
  "ASSIGN",
  "WHILE",
  "RETURN",
  "LENGTH",
  "HTIMES",
  "USE",
  "NEGATIVE",
  "INDEX",
  "USCORE",
  "FUNC_CALL",
  "BLOCK",
  "IXI",
  "FUNC_DEF",
  "INT",
  "MIN_INT",
  "ID",
  "STRING",
  "CHAR"
  };
}

